# Test environment settings
fakeweb_enable: true
default_user:
  id: 'shouta.morimoto@gmail.com'
  password: 'secret'

# Eijiro settings
urls:
  login_post_url: 'https://eowp.alc.co.jp/pkmslogin.form'
  login_get_url: 'https://eowp.alc.co.jp/login'
  wordbook_ej_url: 'http://eowp.alc.co.jp/wordbook/ej'
