# Test environment settings
fakeweb_enable: true
default_user:
  id: 'shouta.morimoto@gmail.com'
  password: 'secret'

# Eijiro settings
base_url: '://eowp.alc.co.jp/' # should not include 'http' or 'https'
paths:
  login:
    path: 'login'
    proto: 'https'
  wordbook_ej:
    path: 'wordbook/ej'
    proto: 'http'
